# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48df94a8ce7cd769c7834980bf6996f817e11021706c297ff45cf0f2b8522a514f640bf6e4bed3b16d7948be61a04e7f5d1ef294665688601ca7f5d187001a42

test:
  secret_key_base: ab7e75f6d4f77d2fc42380a01b790c3eadaf34fb3f89238c39ebc3e01f0acc4042c5313636c612f8f9ff0f70b96b768dd698f0b9fffedab9a8837113113209f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
